### ISSUE TITLE
Cannot download the kratos binary anymore

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-framework#52]
``` python
(simphony)enthought@simphony-base:~/simphony-framework$ make kratos
rm -Rf src/kratos
mkdir -p src/kratos
wget https://web.cimne.upc.edu/users/croig/data/kratos-simphony.tgz -O src/kratos/kratos.tgz
--2015-08-06 10:51:22--  https://web.cimne.upc.edu/users/croig/data/kratos-simphony.tgz
Resolving web.cimne.upc.edu (web.cimne.upc.edu)... 147.83.143.54
Connecting to web.cimne.upc.edu (web.cimne.upc.edu)|147.83.143.54|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-08-06 10:51:22 ERROR 403: Forbidden.
make: *** [kratos] Error 8

```

This bug is **critical** since it does not allow the continues integration to run or anyother integration work to take place without disabling kratos from the framework

**Comment by itziakos** [comment]
@nathanfranklin  and @roigcarlo

**Comment by roigcarlo** [comment]
@nathanfranklin, @itziakos 

There have been some problems with the servers in CIMNE where the code is hosted due to a maintenance ( there will be another one on 11/08/2015). It has already been reported.

I understand that this is critical but there is nothing I can do to fix this until we have somewhere to host the code or the current servers are available again.

**Comment by itziakos** [comment]
Thanks @roigcarlo, I was not aware of the maintenance. Do you know when the server is coming back?

**Comment by roigcarlo** [comment]
It should already be back. It looks like the Kratos project ftp is accessible. I will upload the build there and create a PR as soon as it ready.

**Comment by itziakos** [comment]
I guess that the personal repos will be back soon also. No need to make changes.

**Comment by roigcarlo** [comment]
The problem with the personal repo where is hosted right now is that is a web repo, and hence the storage and download speed are very limited, also as you can see is the first thing to go down and the last one to get ready if something fails 

If you don't mind, I prefer to have it in the official Kratos host along with the sources, this is critical and usually is the first server to be ready after a fail.
Actually the only reason for not being there in the first place is because I hadn't privileges to upload anything.

**Comment by itziakos** [comment]
No problem. Thanks for looking into the issue

**Comment by stefanoborini** [comment]
Solved. Closing
